# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-28 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
        migrations.CreateModel(
            name='Prospect_resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=20)),
                ('NAME', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PROSPECT_RESOURCE',
            },
        ),
        
    ]
