# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-30 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpage', '0002_prospect_resourcemore_prospect_trace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect_condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=20)),
                ('NAME', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PROSPECT_CONDITION',
            },
        ),
        migrations.CreateModel(
            name='Prospect_media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=20)),
                ('NAME', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PROSPECT_MEDIA',
            },
        ),
        migrations.CreateModel(
            name='Prospect_requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=20)),
                ('NAME', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PROSPECT_REQUIREMENT',
            },
        ),
    ]
