# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-30 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testpage', '0003_prospect_condition_prospect_media_prospect_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CUSTMAST',
            fields=[
                ('CUSCOD', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('SNAM', models.CharField(max_length=8)),
                ('NAME1', models.CharField(max_length=50)),
                ('NAME2', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CUSTMAST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OFFICER',
            fields=[
                ('CODE', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'OFFICER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SETCOLOR',
            fields=[
                ('COLORCOD', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('COLORDES', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'SETCOLOR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SETMODEL',
            fields=[
                ('MODELCOD', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('SUBMODEL', models.CharField(max_length=20)),
                ('MODELDES', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'SETMODEL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prospect_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROSPECTDT', models.DateField(blank=True, null=True)),
                ('CUST_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('CUST_LNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('CUST_TEL1', models.CharField(blank=True, max_length=20, null=True)),
                ('CUST_TEL2', models.CharField(blank=True, max_length=20, null=True)),
                ('CUST_TEL3', models.CharField(blank=True, max_length=20, null=True)),
                ('CUST_NOCARD', models.CharField(blank=True, max_length=20, null=True)),
                ('CUST_BIRTHDT', models.DateField(blank=True, null=True)),
                ('CUST_EMAIL', models.CharField(blank=True, max_length=100, null=True)),
                ('SALES_PRICE', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('STATUS_PROSPECT', models.CharField(choices=[('A', 'Active'), ('C', 'Cancel')], default='A', max_length=1)),
                ('MEMO', models.CharField(blank=True, max_length=1024, null=True)),
                ('STATUS_CRE', models.CharField(choices=[('A', 'Active'), ('C', 'Cancel')], default='A', max_length=1)),
                ('RECEIVEDT', models.DateField(blank=True, null=True)),
                ('MATCHDT', models.DateField(blank=True, null=True)),
                ('DELIVERYDT', models.DateField(blank=True, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('ADVISER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testpage.CUSTMAST')),
                ('COLOR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testpage.SETCOLOR')),
                ('MEDIA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testpage.Prospect_media')),
                ('MODEL', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testpage.SETMODEL')),
                ('REQUIREMENT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testpage.Prospect_requirement')),
                ('RESOURCE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testpage.Prospect_resource')),
                ('RESOURCEMORE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testpage.Prospect_resourcemore')),
                ('SALES_CONSULTANT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testpage.OFFICER')),
                ('TERM_CONDITION', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testpage.Prospect_condition')),
                ('TRACE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testpage.Prospect_trace')),
            ],
            options={
                'db_table': 'PROSPECT_TEST',
                'managed': False,
            },
        ),
    ]
