# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-14 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpage', '0005_invtran_secret'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospect_test',
            options={},
        ),
    ]
